user2 = User(username = "d_targaryen", password = "unburnt")
db.session.add(user2)
db.session.commit()
team1 = Team(team_name = "House Stark", user_id = 1)
team2 = Team(team_name = "Stormborn", user_id = 2)
db.session.add_all([team1, team2])
db.session.commit()
project1 = Project(project_name = "Take back Winterfell!", description = "Ramsay Bolton has taken Winterfell, and we must take it back for the North!", completed = False, team_id = 1)
project2 = Project(project_name = "Win the Iron Throne", description = "The throne was stolen from the Targaryen's and Danny must rule on it once again.", completed = False, team_id = 2)
db.session.add_all([project1, project2])
db.session.commit()
